name: Generate mapping.json

on:
  push:
    paths:
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    # Grant write permissions to the GITHUB_TOKEN
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          # Use the token with write permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        working-directory: ./scripts
        run: npm install

      - name: Generate mapping.json
        working-directory: ./scripts
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: npm run generate

      - name: Commit mapping.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mapping.json
          # Check if there are changes to commit
          if ! git diff --cached --quiet; then
            git commit -m "chore: update mapping.json"
            git push
          else
            echo "No changes in mapping.json, skipping commit."
          fi
